name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
     - 'package.json'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from package.json
      id: package_version
      run: echo "::set-output name=VERSION::$(jq -r '.version' package.json)"
      
    - name: Cache Docker Layer
      uses: actions/cache@v2
      with:
        path: /tmp/.docker
        key: ${{ runner.os }}-docker-${{ steps.package_version.outputs.VERSION }}
        restore-keys: ${{ runner.os }}-docker-
        
    - name: Build the Docker image
      if: steps.cache.outputs.cache-hit != 'true'
      run: docker build . --file Dockerfile --tag gearbox:${{ steps.package_version.outputs.VERSION }}
