name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Extract tag name
      id: get_version
      run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gearbox:${{ steps.get_version.outputs.version }}
